# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8effeb50-01d2-4e51-9802-b47d369dedd5";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/17DC-2F14";
      fsType = "vfat";
    };

  fileSystems."/GitRepos" =
    { device = "/dev/disk/by-uuid/8effeb50-01d2-4e51-9802-b47d369dedd5";
      fsType = "btrfs";
      options = [ "subvol=@GitRepos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8effeb50-01d2-4e51-9802-b47d369dedd5";
      fsType = "btrfs";
      options = [ "subvol=@nixos/home" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/8effeb50-01d2-4e51-9802-b47d369dedd5";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
